nebullvm/api/frontend/torch.py
nebullvm/converters/torch_converters.py
nebullvm/inference_learners/openvino.py
nebullvm/inference_learners/tvm.py
nebullvm/installers/install_tvm_prerequisites.sh
nebullvm/optimizers/multi_compiler.py
nebullvm/optimizers/tvm.py
requirements.txt
setup.py

Fix the bugs in the OpenVino and TVM learners (issues #9 and #11).
Solve #8 with a temporary fix, i.e. nebullvm will not support the latest version of tensorflow (2.8.0).

Fix bugs in InferenceLearners and solve numpy issue on ubuntu systems.

---

nebullvm/api/frontend/hugginface.py
nebullvm/api/frontend/huggingface.py
nebullvm/api/frontend/tf.py
nebullvm/api/frontend/torch.py
nebullvm/base.py
nebullvm/config.py
nebullvm/converters/converters.py
nebullvm/converters/tensorflow_converters.py
nebullvm/converters/torch_converters.py
nebullvm/inference_learners/base.py
nebullvm/inference_learners/onnx.py
nebullvm/inference_learners/openvino.py
nebullvm/inference_learners/tensor_rt.py
nebullvm/inference_learners/tvm.py
nebullvm/installers/installers.py
nebullvm/optimizers/__init__.py
nebullvm/optimizers/multi_compiler.py
nebullvm/optimizers/onnx.py
nebullvm/optimizers/openvino.py
nebullvm/optimizers/tensor_rt.py
nebullvm/optimizers/tests/test_onnx.py
nebullvm/optimizers/tests/test_openvino.py
nebullvm/optimizers/tests/test_tensor_rt.py
nebullvm/optimizers/tests/test_tvm.py
nebullvm/optimizers/tests/utils.py
nebullvm/optimizers/tvm.py
nebullvm/utils/tf.py
nebullvm/utils/torch.py
requirements.txt

Closes #16. Implement a new API for optimising HuggingFace transformers. The PR adds support for dynamic shapes for both PyTorch and TensorFlow models too.

Add huggingface API

---

README.md
nebullvm/__init__.py
nebullvm/api/frontend/huggingface.py
nebullvm/api/frontend/onnx.py
nebullvm/api/frontend/tf.py
nebullvm/api/frontend/torch.py
nebullvm/base.py
nebullvm/config.py
nebullvm/converters/tensorflow_converters.py
nebullvm/converters/torch_converters.py
nebullvm/inference_learners/base.py
nebullvm/inference_learners/onnx.py
nebullvm/inference_learners/openvino.py
nebullvm/inference_learners/tensor_rt.py
nebullvm/inference_learners/tvm.py
nebullvm/installers/install_tvm_prerequisites.sh
nebullvm/installers/installers.py
nebullvm/optimizers/base.py
nebullvm/optimizers/extra.py
nebullvm/optimizers/multi_compiler.py
nebullvm/optimizers/onnx.py
nebullvm/optimizers/openvino.py
nebullvm/optimizers/tensor_rt.py
nebullvm/optimizers/tvm.py
nebullvm/quantizers/base.py
nebullvm/quantizers/onnx_quantizer.py
nebullvm/quantizers/tests/test_onnx_quantizer.py
nebullvm/utils/onnx.py

Closes #27. It implements the quantization at ONNX level.

Add quantization

---

README.md
nebullvm/inference_learners/onnx.py
setup.py

Fix bug with multiple models running in parallels

---

nebullvm/inference_learners/openvino.py

Fix the retrieval of input shape from the openvino network

---

.github/workflows/tests.yml

A CI/CD pipeline has been added in order to run tests every time a new push or pull request is performed on the main branch

Added CI/CD pipeline with GitHub Actions

---

docs/conf.py
nebullvm/inference_learners/openvino.py
nebullvm/inference_learners/tensor_rt.py
nebullvm/transformations/tensor_tfms.py

Closes #38, #59.  This PR contains the code written in #47 and the code fixing #59.

Update OpenVino and Fix bug with TensorRT

---

nebullvm/optimizers/openvino.py

fix(OpenVINO): parse input sizes of 1d tensors

---

nebullvm/measure.py

Signed-off-by: reiase <reiase@gmail.com>
/close #77

use median latency instead of mean latency

---

nebullvm/api/frontend/tf.py
nebullvm/api/functions.py
nebullvm/compressors/intel.py
nebullvm/compressors/scripts/neural_magic_training.py
nebullvm/compressors/sparseml.py
nebullvm/converters/converters.py
nebullvm/converters/tensorflow_converters.py
nebullvm/inference_learners/base.py
nebullvm/inference_learners/onnx.py
nebullvm/inference_learners/openvino.py
nebullvm/inference_learners/tensor_rt.py
nebullvm/inference_learners/tensorflow.py
nebullvm/inference_learners/tvm.py
nebullvm/installers/installers.py
nebullvm/measure.py
nebullvm/optimizers/quantization/onnx.py
nebullvm/optimizers/quantization/tensorflow.py
nebullvm/optimizers/tensor_rt.py
nebullvm/optimizers/tensorflow.py
nebullvm/pipelines/steps.py
nebullvm/transformations/precision_tfms.py
nebullvm/utils/benchmark.py
nebullvm/utils/onnx.py
nebullvm/utils/optional_modules.py
nebullvm/utils/tf.py
requirements.txt
setup.py

- Support ignore_compilers also for torchscript and tflite
- Bug on quantization half onnx: posix path instead of string
- Bug on tensor rt quantization: numpy array passed to inference learner instead of tensor.
- Tensorflow now will not be installed by default by nebullvm

bugfix & optional tensorflow implementation

---

nebullvm/installers/install_tensor_rt.sh

Fixes `shell` not found in `install_tensor_rt.sh`

---

.github/workflows/tests.yml
Dockerfile
apps/accelerate/speedster/README.md
apps/accelerate/speedster/speedster/api/tests/test_huggingface.py
apps/accelerate/speedster/speedster/api/tests/test_tensorflow.py
azure-pipelines.yml
nebullvm/installers/auto_installer.py
nebullvm/installers/installers.py
nebullvm/installers/tests/test_install_frameworks.py
notebooks/speedster/README.md
notebooks/speedster/huggingface/Accelerate_Hugging_Face_PyTorch_BERT_with_Speedster.ipynb
notebooks/speedster/huggingface/Accelerate_Hugging_Face_PyTorch_DistilBERT_with_Speedster.ipynb
notebooks/speedster/huggingface/Accelerate_Hugging_Face_PyTorch_GPT2_with_Speedster.ipynb
notebooks/speedster/huggingface/Accelerate_Hugging_Face_TensorFlow_BERT_with_Speedster.ipynb
notebooks/speedster/onnx/Accelerate_ONNX_ResNet50_with_Speedster.ipynb
notebooks/speedster/pytorch/Accelerate_PyTorch_ResNet50_with_Speedster.ipynb
notebooks/speedster/pytorch/Accelerate_PyTorch_YOLO_with_Speedster.ipynb
notebooks/speedster/pytorch/Accelerate_fast_ai_Resnet34_with_Speedster.ipynb
notebooks/speedster/tensorflow/Accelerate_Tensorflow_ResNet50_with_Speedster.ipynb

This PR includes:
**New features**
- The docker container is now built and pushed automatically in the Azure Pipeline
**Changes**
- Renamed the _frameworks_ argument in the `auto_install` function to _backends_, and modified how the single frameworks are specified. Before all the frameworks that had to be used from speedster to optimize the models had to be specified in a list, now new options are introduced to cover the most common use cases:
| Option                 | Description                                                                                                         |
|:-----------------------|:--------------------------------------------------------------------------------------------------------------------|
| all                    | Installs all the backends …

Add docker auto-build in in Azure Pipelines and modify auto_install function 

---

apps/accelerate/speedster/speedster/root_op.py
nebullvm/tools/logger.py

This PR modifies the logs colours and adds further information and tips when no better model is found by speedster

Modify Logs colours 

---

nebullvm/operations/optimizations/base.py
nebullvm/tools/utils.py

Fix bug in checking data format

---

apps/accelerate/chatllama/README.md
apps/accelerate/chatllama/chatllama/rlhf/reward.py

Change distillate to distill

---

CONTRIBUTING.md

Slipped in some fresh guidelines into the CONTRIBUTING.md file

Edit CONTRIBUTING.md file

---

apps/accelerate/chatllama/README.md
apps/accelerate/chatllama/generate_dataset.py
apps/accelerate/chatllama/setup.py

Hey @diegofiori!
Thank you for making `chatllama` public! I was looking into how to create my own dataset and came across this issue: 
- [https://github.com/nebuly-ai/nebullvm/issues/200](https://github.com/nebuly-ai/nebullvm/issues/200)
In the meantime, I decided to experiment with langchain agents to generate a dataset. During my experimentation, I encountered a few small bugs which I have fixed in this pull request:
1. I added openai to the dependencies
2. I updated the readme with instructions on how to add the openai api key as an environment variable
3. I called the `main()` function in `generate_dataset.py` (currently the script executes but nothing is called).
super excited for your training example!

ChatLlaMA fixes

---

nebullvm/installers/installers.py
nebullvm/optional_modules/neural_compressor.py
requirements.txt
setup.py

Fix ImportError in google colab

---

apps/accelerate/chatllama/chatllama/llama_model.py

while token_id is -1, embedding will cause out of bounds.
https://github.com/nebuly-ai/nebullvm/blob/ca085a979b5b596bf0ecd477e4c4deff3725661c/apps/accelerate/chatllama/chatllama/llama_model.py#L482
partial error message:
```plain
/opt/conda/conda-bld/pytorch_1659484808560/work/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [120,0,0], thread: [24,0,0] Assertion `srcIndex < srcSelectDimSize
` failed.
/opt/conda/conda-bld/pytorch_1659484808560/work/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [120,0,0], thread: [25,0,0] Assertion `srcIndex < srcSelectDimSize
` failed.
/opt/conda/conda-bld/pytorch_1659484808560/work/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [120,0,0], thread: [26,0,0] Assertion `srcIndex < …
```

[Chatllama] fix embedding out of bounds

---

notebooks/speedster/onnx/Accelerate_ONNX_ResNet50_with_Speedster.ipynb
notebooks/speedster/pytorch/Accelerate_PyTorch_ResNet50_with_Speedster.ipynb
notebooks/speedster/pytorch/Accelerate_PyTorch_YOLOv8_with_Speedster.ipynb
notebooks/speedster/pytorch/Accelerate_fast_ai_Resnet34_with_Speedster.ipynb
notebooks/speedster/tensorflow/Accelerate_Tensorflow_ResNet50_with_Speedster.ipynb

Fix issue with visualization of some jupyter notebooks on github

---

apps/accelerate/speedster/speedster/root_op.py

[Speedster] Fix bug when diffusers is not installed

---

nebullvm/operations/inference_learners/base.py
nebullvm/operations/inference_learners/huggingface.py
nebullvm/tools/diffusers.py

- Expose property "name" on BaseInferenceLearner
- Fix postprocess_diffuser params type (DiffusionPipeline -> StableDiffusionPipeline)

[Nebullvm] Improve typing

---

nebullvm/optional_modules/torch.py

Same as https://github.com/nebuly-ai/nebullvm/pull/296 - add missing modules

Add Generator and FloatTensor to torch class

---

notebooks/speedster/pytorch/Accelerate_PyTorch_ViT_with_Speedster.ipynb

I added a new notebook demonstrating how to optimize PyTorch VisionTransformer using Speedster.

ViT pytorch speedster notebook added
